export const GET_MINERALS = 'GET_MINERALS';
export const FILTER_MINERALS = 'FILTER_MINERALS';
export const GET_LITHOLOGY ='GET_LITHOLOGY';
export const FILTER_LITHOLOGY = 'FILTER_LITHOLOGY';
export const GET_INTERVAL = 'GET_INTERVAL';
export const SEARCH_INTERVAL = 'SEARCH_INTERVAL';
export const GET_POLYGON = 'GET_POLYGON';
